import fs from 'fs';

const RAW_TOOLS = [
  // Creator Toolkit
  { id: "youtube-title-checker", name: "YouTube Title Checker", description: "Optimize your video titles for maximum CTR and searchability.", categoryId: "creator"},
  { id: "hashtag-generator", name: "Hashtag Generator", description: "Generate relevant hashtags for Instagram, TikTok, and Twitter.", categoryId: "creator"},
  { id: "read-time-estimator", name: "Read Time Estimator", description: "Estimate reading time for blog posts and article scripts.", categoryId: "creator"},
  { id: "social-post-preview", name: "Social Post Preview", description: "Preview tweet and post limits safely.", categoryId: "creator"},
  { id: "video-description-template", name: "Description Generator", description: "Generate standard SEO-optimized video description templates.", categoryId: "creator"},

  // Gaming Toolkit
  { id: "kd-calculator", name: "K/D Calculator", description: "Calculate your Kill/Death ratio easily.", categoryId: "gaming"},
  { id: "edpi-calculator", name: "eDPI Calculator", description: "Calculate effective DPI to compare sensitivity with pros.", categoryId: "gaming"},
  { id: "sens-converter", name: "Sensitivity Converter", description: "Convert mouse sensitivity between different shooter games.", categoryId: "gaming"},
  { id: "xp-calculator", name: "XP Goal Calculator", description: "Calculate exactly how many matches you need to level up.", categoryId: "gaming"},
  { id: "aspect-ratio-calc", name: "Aspect Ratio Calculator", description: "Calculate screen resolutions and aspect ratios.", categoryId: "gaming"},

  { id: "remove-duplicate-lines", name: "Remove Duplicate Lines", description: "Remove all duplicate lines from your text.", categoryId: "text"},
  { id: "sort-lines", name: "Sort Lines", description: "Sort lines alphabetically A-Z.", categoryId: "text"},
  { id: "reverse-lines", name: "Reverse Lines", description: "Reverse the order of lines.", categoryId: "text"},
  { id: "character-counter", name: "Character Counter", description: "Count characters with and without spaces.", categoryId: "text"},
  { id: "extract-emails", name: "Extract Emails", description: "Extract all email addresses from text.", categoryId: "text"},
  { id: "extract-urls", name: "Extract URLs", description: "Extract all website links from text.", categoryId: "text"},
  { id: "remove-empty-lines", name: "Remove Empty Lines", description: "Remove all empty or whitespace-only lines.", categoryId: "text"},
  { id: "text-compare", name: "Text Compare", description: "Compare two text snippets.", categoryId: "text"},
  { id: "find-and-replace", name: "Find and Replace", description: "Find and replace text using simple strings or regular expressions.", categoryId: "text"},
  { id: "csv-cleaner", name: "CSV Cleaner", description: "Remove empty rows and trim spaces from CSV cells.", categoryId: "text"},
  { id: "whitespace-remover", name: "Whitespace Remover", description: "Clean up extra spaces.", categoryId: "text"},
  { id: "text-formatter", name: "Text Formatter", description: "Auto-format spaces and punctuation.", categoryId: "text"},
  { id: "word-counter", name: "Word Counter", description: "Count words, characters, sentences, and paragraphs in your text.", categoryId: "text"},
  {
    id: "case-converter",
    name: "Convert Case",
    description: "Change text to uppercase, lowercase, title case, and more.",
    categoryId: "text",
  },
  {
    id: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate, and beautify your JSON data.",
    categoryId: "developer",
  },
  {
    id: "base64-encoder",
    name: "Base64 Encoder",
    description: "Encode text or data to Base64 format.",
    categoryId: "developer",
  },
  { id: "profit-calculator", name: "Profit Calculator", description: "Calculate your margin, markup, and gross profit.", categoryId: "seller"},
  { id: "roi-calculator", name: "ROI Calculator", description: "Calculate Return on Investment for your campaigns and products.", categoryId: "seller"},
  { id: "marketplace-fee-calculator", name: "Marketplace Fee Calculator", description: "Calculate fees for selling on platforms like Amazon and eBay.", categoryId: "seller"},
  { id: "pricing-calculator", name: "Pricing Calculator", description: "Determine the optimal selling price based on cost and desired margin.", categoryId: "seller"},
  { id: "break-even-calculator", name: "Break-Even Calculator", description: "Find out how many units you need to sell to cover costs.", categoryId: "seller"},
  { id: "margin-calculator", name: "Margin Calculator", description: "Quickly calculate gross margin percentage.", categoryId: "seller"},
  { id: "discount-calculator", name: "Discount Calculator", description: "Calculate sale prices and discount amounts.", categoryId: "seller"},
  { id: "sales-tax-calculator", name: "Sales Tax Calculator", description: "Calculate prices before and after sales tax.", categoryId: "seller"},
  { id: "revenue-forecast", name: "Revenue Forecast Tool", description: "Project your sales and revenue over time.", categoryId: "seller"},
  { id: "product-cost-calculator", name: "Product Cost Calculator", description: "Calculate total landed cost for a product.", categoryId: "seller"},
  {
    id: "merge-pdf",
    name: "Merge PDF",
    description: "Combine multiple PDF files into one.",
    categoryId: "pdf",
  },
  { id: "split-pdf", name: "Split PDF", description: "Separate one page or a whole set for easy conversion into independent PDF files.", categoryId: "pdf"},
  { id: "compress-pdf", name: "Compress PDF", description: "Reduce file size while optimizing for maximal PDF quality.", categoryId: "pdf"},
  { id: "rotate-pdf", name: "Rotate PDF", description: "Rotate your PDFs the way you need them.", categoryId: "pdf"},
  { id: "reorder-pdf", name: "Reorder PDF Pages", description: "Change the order of pages in your PDF.", categoryId: "pdf"},
  { id: "extract-pdf", name: "Extract Pages", description: "Get a new document containing only the desired pages.", categoryId: "pdf"},
  { id: "delete-pdf", name: "Delete Pages", description: "Remove empty pages or useless pages from your PDF.", categoryId: "pdf"},
  { id: "watermark-pdf", name: "Add Watermark", description: "Stamp an image or text over your PDF in seconds.", categoryId: "pdf"},
  { id: "page-numbers-pdf", name: "Add Page Numbers", description: "Add page numbers into PDFs with ease.", categoryId: "pdf"},
  { id: "protect-pdf", name: "Protect PDF", description: "Encrypt your PDF with a password.", categoryId: "pdf"},
  { id: "unlock-pdf", name: "Unlock PDF", description: "Remove PDF password security.", categoryId: "pdf"},
  { id: "pdf-to-jpg", name: "PDF to JPG", description: "Convert each PDF page into a JPG.", categoryId: "pdf"},
  { id: "jpg-to-pdf", name: "JPG to PDF", description: "Convert JPG images to PDF.", categoryId: "pdf"},
  { id: "png-to-pdf", name: "PNG to PDF", description: "Convert PNG images to PDF.", categoryId: "pdf"},
  { id: "pdf-to-png", name: "PDF to PNG", description: "Convert each PDF page into a PNG.", categoryId: "pdf"},
  { id: "pdf-to-text", name: "PDF to Text", description: "Extract text from your PDF.", categoryId: "pdf"},
  { id: "pdf-metadata", name: "PDF Metadata Viewer", description: "View and edit PDF metadata.", categoryId: "pdf"},
  { id: "alternate-mix-pdf", name: "Alternate & Mix", description: "Alternate pages from multiple PDFs.", categoryId: "pdf"},
  { id: "split-by-pages", name: "Split by Pages", description: "Split PDF into multiple files based on page numbers.", categoryId: "pdf"},
  { id: "split-by-bookmarks", name: "Split by Bookmarks", description: "Split PDF using existing bookmarks.", categoryId: "pdf"},
  { id: "split-in-half", name: "Split in Half", description: "Split a PDF exactly down the middle.", categoryId: "pdf"},
  { id: "split-by-size", name: "Split by Size", description: "Split a PDF based on target file size.", categoryId: "pdf"},
  { id: "split-by-text", name: "Split by Text", description: "Split a PDF whenever specific text appears.", categoryId: "pdf"},
  { id: "edit-pdf", name: "Edit PDF", description: "Add text, shapes, and images directly to your PDF.", categoryId: "pdf"},
  { id: "fill-sign-pdf", name: "Fill & Sign", description: "Fill out PDF forms and sign them.", categoryId: "pdf"},
  { id: "create-forms-pdf", name: "Create Forms", description: "Create interactive PDF forms.", categoryId: "pdf"},
  { id: "flatten-pdf", name: "Flatten PDF", description: "Flatten forms and annotations.", categoryId: "pdf"},
  { id: "pdf-to-excel", name: "PDF to Excel", description: "Convert PDF tables to Excel spreadsheets.", categoryId: "pdf"},
  { id: "pdf-to-ppt", name: "PDF to PowerPoint", description: "Convert PDF to PowerPoint presentation.", categoryId: "pdf"},
  { id: "pdf-to-word", name: "PDF to Word", description: "Convert PDF to Word document.", categoryId: "pdf"},
  { id: "html-to-pdf", name: "HTML to PDF", description: "Convert HTML webpages to PDF.", categoryId: "pdf"},
  { id: "word-to-pdf", name: "Word to PDF", description: "Convert Word documents to PDF.", categoryId: "pdf"},
  { id: "bates-numbering", name: "Bates Numbering", description: "Add bates numbering to your PDF.", categoryId: "pdf"},
  { id: "create-bookmarks", name: "Create Bookmarks", description: "Add bookmarks to your PDF.", categoryId: "pdf"},
  { id: "crop-pdf", name: "Crop PDF", description: "Crop page margins of a PDF.", categoryId: "pdf"},
  { id: "extract-images-pdf", name: "Extract Images", description: "Extract all images from a PDF.", categoryId: "pdf"},
  { id: "grayscale-pdf", name: "Grayscale", description: "Convert PDF to black and white.", categoryId: "pdf"},
  { id: "header-footer-pdf", name: "Header & Footer", description: "Add customized headers and footers.", categoryId: "pdf"},
  { id: "n-up-pdf", name: "N-up", description: "Print multiple pages on a single sheet.", categoryId: "pdf"},
  { id: "rename-pdf", name: "Rename", description: "Rename your PDF file easily.", categoryId: "pdf"},
  { id: "repair-pdf", name: "Repair", description: "Repair a corrupted PDF file.", categoryId: "pdf"},
  { id: "resize-pdf", name: "Resize", description: "Resize PDF page dimensions.", categoryId: "pdf"},
  { id: "remove-annotations-pdf", name: "Remove Annotations", description: "Remove comments, highlights, and annotations.", categoryId: "pdf"},
  { id: "deskew-pdf", name: "Deskew", description: "Straighten scanned PDF pages.", categoryId: "pdf"},
  { id: "ocr-pdf", name: "OCR PDF", description: "Make scanned text searchable.", categoryId: "pdf"},
  { id: "automate-pdf", name: "Automate", description: "Create PDF processing workflows.", categoryId: "pdf"},
  { id: "json-validator", name: "JSON Validator", description: "Validate and find errors in your JSON data.", categoryId: "developer"},
  { id: "regex-tester", name: "Regex Tester", description: "Test and debug your regular expressions.", categoryId: "developer"},
  { id: "jwt-decoder", name: "JWT Decoder", description: "Decode and inspect JSON Web Tokens.", categoryId: "developer"},
  { id: "jwt-inspector", name: "JWT Inspector", description: "Analyze JSON Web Tokens.", categoryId: "developer"},
  { id: "base64-decoder", name: "Base64 Decoder", description: "Decode Base64 strings to readable text.", categoryId: "developer"},
  { id: "url-encoder-decoder", name: "URL Encoder/Decoder", description: "Encode or decode strings for URLs.", categoryId: "developer"},
  { id: "color-converter", name: "Color Converter", description: "Convert between HEX, RGB, HSL, and more.", categoryId: "developer"},
  { id: "api-tester", name: "API Request Tester", description: "Test HTTP API endpoints directly from the browser.", categoryId: "developer"},
  { id: "uuid-generator", name: "UUID Generator", description: "Generate random, unique UUIDs.", categoryId: "developer"},
  { id: "hash-generator", name: "Hash Generator", description: "Generate MD5, SHA-1, SHA-256 hashes.", categoryId: "developer"},
  { id: "sql-formatter", name: "SQL Formatter", description: "Format and beautify SQL queries.", categoryId: "developer"},
  { id: "xml-formatter", name: "XML Formatter", description: "Format and beautify XML code.", categoryId: "developer"},
  { id: "csv-to-json", name: "CSV to JSON", description: "Convert CSV tables to JSON format.", categoryId: "developer"},
  { id: "json-to-csv", name: "JSON to CSV", description: "Convert JSON arrays to CSV format.", categoryId: "developer"},
  { id: "gpa-calculator", name: "GPA Calculator", description: "Calculate your semester or cumulative GPA.", categoryId: "student"},
  { id: "grade-calculator", name: "Grade Calculator", description: "Determine what you need on the final to get your desired grade.", categoryId: "student"},
  { id: "citation-formatter", name: "Citation Formatter", description: "Format citations in APA, MLA, or Chicago style.", categoryId: "student"},
  { id: "study-schedule", name: "Study Schedule Generator", description: "Create a balanced study schedule based on your subjects.", categoryId: "student"},
  { id: "exam-countdown", name: "Exam Countdown Tracker", description: "Track days left until your exams.", categoryId: "student"},
  { id: "flashcard-exporter", name: "Flashcard Exporter", description: "Convert notes into flashcard formats suitable for Anki or Quizlet.", categoryId: "student"},
  { id: "reading-time", name: "Reading Time Calculator", description: "Estimate how long it will take to read a text or book chapter.", categoryId: "student"},
  { id: "assignment-planner", name: "Assignment Planner", description: "Break down large assignments into manageable steps.", categoryId: "student"},
  { id: "note-formatter", name: "Note Formatter", description: "Format and clean up your raw text or unstructured notes.", categoryId: "student"},
  { id: "semester-planner", name: "Semester Planner", description: "Plan your courses and milestones for the semester.", categoryId: "student"},

  // --- NEWLY ADDED TOOLS ---

  // 1. PDF Tools
  { id: "pdf-metadata-editor", name: "PDF Metadata Editor", description: "Strip or edit author, title, and creation date for privacy.", categoryId: "pdf"},
  { id: "pdf-redactor", name: "PDF Redactor", description: "Permanently draw black boxes over sensitive PDF info.", categoryId: "pdf"},
  { id: "compare-pdfs", name: "Compare PDFs", description: "A visual diff tool that overlays two PDFs.", categoryId: "pdf"},
  { id: "pdf-editor", name: "PDF Editor", description: "Add text, draw, and sign PDFs directly in your browser.", categoryId: "pdf"},

  // 2. Developer Tools
  { id: "cron-job-generator", name: "Cron Job Generator", description: "Translate complex Cron syntax into plain English.", categoryId: "developer"},
  { id: "yaml-json-converter", name: "YAML <> JSON", description: "Convert between YAML and JSON formats.", categoryId: "developer"},
  { id: "jwt-builder", name: "JWT Builder", description: "Create and sign custom JWTs locally for testing.", categoryId: "developer"},

  // 3. Text Tools
  { id: "markdown-to-html", name: "Markdown to HTML", description: "Real-time previewer and converter.", categoryId: "text"},
  { id: "diff-viewer", name: "Diff Viewer", description: "Side-by-side text comparison tool.", categoryId: "text"},
  { id: "lorem-ipsum-generator", name: "Lorem Ipsum Generator", description: "Generate placeholder text easily.", categoryId: "text"},

  // 4. Gaming Tools
  { id: "fov-converter", name: "FOV Converter", description: "Match FOV perfectly across different game engines.", categoryId: "gaming"},
  { id: "mouse-polling-checker", name: "Mouse Polling Rate", description: "Measure the Hz polling rate of your mouse.", categoryId: "gaming"},
  { id: "reaction-time-tester", name: "Reaction Time Tester", description: "Click when green to test your reflexes.", categoryId: "gaming"},

  // 5. Student Tools
  { id: "pomodoro-timer", name: "Pomodoro Timer", description: "Customizable study timer with browser notifications.", categoryId: "student"},
  { id: "synonym-swapper", name: "Word Synonym Swapper", description: "Help rewrite sentences using local libraries.", categoryId: "student"},
  { id: "interactive-flashcards", name: "Interactive Flashcards", description: "Auto-generates flip-cards from text.", categoryId: "student"},

  // 6. Seller / Business Tools
  { id: "local-invoice-generator", name: "Local Invoice Generator", description: "Generate PDF invoices offline.", categoryId: "seller"},
  { id: "qr-barcode-generator", name: "QR & Barcode Generator", description: "Generate scannable codes for links or VCards.", categoryId: "seller"},
  { id: "cpm-calculator", name: "CPM Calculator", description: "Calculate Cost Per Mille ad spend.", categoryId: "seller"},

  // 7. Creator Tools
  { id: "thumbnail-safe-zone", name: "Thumbnail Safe-Zone", description: "Check if text is blocked by YouTube UI elements.", categoryId: "creator"},
  { id: "exif-stripper", name: "EXIF Data Stripper", description: "Remove location and camera data from images.", categoryId: "creator"},

  // 8. Security & Privacy Tools
  { id: "password-generator", name: "Password Generator", description: "Customizable random password creator.", categoryId: "security"},
  { id: "password-strength-checker", name: "Password Strength", description: "Estimate time-to-crack locally.", categoryId: "security"},
  { id: "local-hash-generator", name: "Local Hash Generator", description: "Instantly generate MD5, SHA-256, or Bcrypt hashes.", categoryId: "security"},
  { id: "pgp-encrypt-decrypt", name: "PGP Encrypt/Decrypt", description: "Securely lock or unlock messages locally.", categoryId: "security"},

  // 9. Network & Webmaster Tools
  { id: "cidr-subnet-calculator", name: "CIDR / Subnet Calculator", description: "Calculate IP subnets and masks.", categoryId: "network"},
  { id: "utm-link-builder", name: "UTM Link Builder", description: "Generate tracking URLs for campaigns.", categoryId: "network"},
  { id: "url-parser", name: "URL Parser", description: "Break down massive dirty URLs into query parameters.", categoryId: "network"},

  // 10. Media & Image Tools
  { id: "svg-optimizer", name: "SVG Optimizer", description: "Clean up and minify SVG code offline.", categoryId: "media"},
  { id: "base64-image-converter", name: "Base64 <> Image", description: "Convert between base64 strings and images.", categoryId: "media"},
  { id: "webp-converter", name: "WebP Converter", description: "Compress PNGs/JPGs into WebP instantly.", categoryId: "media"},

  // 11. Design & UI Tools
  { id: "box-shadow-generator", name: "Box Shadow Generator", description: "Create smooth, layered CSS box shadows.", categoryId: "design"},
  { id: "border-radius-generator", name: "Border Radius Generator", description: "Create complex and organic border radius shapes.", categoryId: "design"},
  { id: "gradient-text-generator", name: "Gradient Text Generator", description: "Generate beautiful CSS gradient text effects.", categoryId: "design"},
  { id: "glassmorphism-generator", name: "Glassmorphism Generator", description: "Generate CSS glassmorphism effect.", categoryId: "design"},
  { id: "neumorphism-generator", name: "Neumorphism Generator", description: "Generate CSS neumorphism effect.", categoryId: "design"},
  { id: "css-triangle-generator", name: "CSS Triangle Generator", description: "Generate CSS triangles easily.", categoryId: "design"},
  { id: "svg-blob-generator", name: "SVG Blob Generator", description: "Generate organic SVG blobs.", categoryId: "design"},
  { id: "css-gradient-generator", name: "Gradient Generator", description: "Visual builder for complex CSS gradients.", categoryId: "design"},
  { id: "color-contrast-checker", name: "Color Contrast Checker", description: "Check color contrast against WCAG guidelines.", categoryId: "design"},
  { id: "color-palette-generator", name: "Color Palette Generator", description: "Suggest color schemes based on a hex code.", categoryId: "design"},
  { id: "image-to-colors", name: "Image to Colors", description: "Extract dominant color palette from image.", categoryId: "design"}
];

const toolsConfig = {
  "youtube-title-checker": { isWorking: false },
  "hashtag-generator": { isWorking: false },
  "read-time-estimator": { isWorking: false },
  "social-post-preview": { isWorking: false },
  "video-description-template": { isWorking: false },
  "kd-calculator": { isWorking: false },
  "edpi-calculator": { isWorking: false },
  "sens-converter": { isWorking: false },
  "xp-calculator": { isWorking: false },
  "aspect-ratio-calc": { isWorking: false },
  "remove-duplicate-lines": { isWorking: true },
  "sort-lines": { isWorking: true },
  "reverse-lines": { isWorking: true },
  "character-counter": { isWorking: true },
  "extract-emails": { isWorking: true },
  "extract-urls": { isWorking: true },
  "remove-empty-lines": { isWorking: true },
  "text-compare": { isWorking: true },
  "find-and-replace": { isWorking: true },
  "csv-cleaner": { isWorking: true },
  "whitespace-remover": { isWorking: true },
  "text-formatter": { isWorking: true },
  "word-counter": { isWorking: true },
  "case-converter": { isWorking: true },
  "json-formatter": { isWorking: true },
  "base64-encoder": { isWorking: true },
  "profit-calculator": { isWorking: false },
  "roi-calculator": { isWorking: false },
  "marketplace-fee-calculator": { isWorking: false },
  "pricing-calculator": { isWorking: false },
  "break-even-calculator": { isWorking: false },
  "margin-calculator": { isWorking: false },
  "discount-calculator": { isWorking: false },
  "sales-tax-calculator": { isWorking: false },
  "revenue-forecast": { isWorking: false },
  "product-cost-calculator": { isWorking: false },
  "merge-pdf": { isWorking: true },
  "split-pdf": { isWorking: false },
  "compress-pdf": { isWorking: false },
  "rotate-pdf": { isWorking: false },
  "reorder-pdf": { isWorking: false },
  "extract-pdf": { isWorking: false },
  "delete-pdf": { isWorking: false },
  "watermark-pdf": { isWorking: false },
  "page-numbers-pdf": { isWorking: false },
  "protect-pdf": { isWorking: false },
  "unlock-pdf": { isWorking: false },
  "pdf-to-jpg": { isWorking: false },
  "jpg-to-pdf": { isWorking: false },
  "png-to-pdf": { isWorking: false },
  "pdf-to-png": { isWorking: false },
  "pdf-to-text": { isWorking: false },
  "pdf-metadata": { isWorking: false },
  "alternate-mix-pdf": { isWorking: false },
  "split-by-pages": { isWorking: false },
  "split-by-bookmarks": { isWorking: false },
  "split-in-half": { isWorking: false },
  "split-by-size": { isWorking: false },
  "split-by-text": { isWorking: false },
  "edit-pdf": { isWorking: false },
  "fill-sign-pdf": { isWorking: false },
  "create-forms-pdf": { isWorking: false },
  "flatten-pdf": { isWorking: false },
  "pdf-to-excel": { isWorking: false },
  "pdf-to-ppt": { isWorking: false },
  "pdf-to-word": { isWorking: false },
  "html-to-pdf": { isWorking: false },
  "word-to-pdf": { isWorking: false },
  "bates-numbering": { isWorking: false },
  "create-bookmarks": { isWorking: false },
  "crop-pdf": { isWorking: false },
  "extract-images-pdf": { isWorking: false },
  "grayscale-pdf": { isWorking: false },
  "header-footer-pdf": { isWorking: false },
  "n-up-pdf": { isWorking: false },
  "rename-pdf": { isWorking: false },
  "repair-pdf": { isWorking: false },
  "resize-pdf": { isWorking: false },
  "remove-annotations-pdf": { isWorking: false },
  "deskew-pdf": { isWorking: false },
  "ocr-pdf": { isWorking: false },
  "automate-pdf": { isWorking: false },
  "json-validator": { isWorking: false },
  "regex-tester": { isWorking: false },
  "jwt-decoder": { isWorking: true },
  "jwt-inspector": { isWorking: false },
  "base64-decoder": { isWorking: true },
  "url-encoder-decoder": { isWorking: false },
  "color-converter": { isWorking: false },
  "api-tester": { isWorking: false },
  "uuid-generator": { isWorking: true },
  "hash-generator": { isWorking: false },
  "sql-formatter": { isWorking: false },
  "xml-formatter": { isWorking: false },
  "csv-to-json": { isWorking: false },
  "json-to-csv": { isWorking: false },
  "gpa-calculator": { isWorking: false },
  "grade-calculator": { isWorking: false },
  "citation-formatter": { isWorking: false },
  "study-schedule": { isWorking: false },
  "exam-countdown": { isWorking: false },
  "flashcard-exporter": { isWorking: false },
  "reading-time": { isWorking: false },
  "assignment-planner": { isWorking: false },
  "note-formatter": { isWorking: false },
  "semester-planner": { isWorking: false },
  "pdf-metadata-editor": { isWorking: false },
  "pdf-redactor": { isWorking: false },
  "compare-pdfs": { isWorking: false },
  "pdf-editor": { isWorking: false },
  "cron-job-generator": { isWorking: false },
  "yaml-json-converter": { isWorking: false },
  "jwt-builder": { isWorking: false },
  "markdown-to-html": { isWorking: true },
  "diff-viewer": { isWorking: true },
  "lorem-ipsum-generator": { isWorking: true },
  "fov-converter": { isWorking: false },
  "mouse-polling-checker": { isWorking: false },
  "reaction-time-tester": { isWorking: false },
  "pomodoro-timer": { isWorking: false },
  "synonym-swapper": { isWorking: false },
  "interactive-flashcards": { isWorking: false },
  "local-invoice-generator": { isWorking: false },
  "qr-barcode-generator": { isWorking: false },
  "cpm-calculator": { isWorking: false },
  "thumbnail-safe-zone": { isWorking: false },
  "exif-stripper": { isWorking: false },
  "password-generator": { isWorking: false },
  "password-strength-checker": { isWorking: false },
  "local-hash-generator": { isWorking: false },
  "pgp-encrypt-decrypt": { isWorking: false },
  "cidr-subnet-calculator": { isWorking: false },
  "utm-link-builder": { isWorking: false },
  "url-parser": { isWorking: false },
  "svg-optimizer": { isWorking: false },
  "base64-image-converter": { isWorking: false },
  "webp-converter": { isWorking: false },
  "box-shadow-generator": { isWorking: false },
  "border-radius-generator": { isWorking: false },
  "gradient-text-generator": { isWorking: false },
  "glassmorphism-generator": { isWorking: false },
  "neumorphism-generator": { isWorking: false },
  "css-triangle-generator": { isWorking: false },
  "svg-blob-generator": { isWorking: false },
  "css-gradient-generator": { isWorking: false },
  "color-contrast-checker": { isWorking: false },
  "color-palette-generator": { isWorking: false },
  "image-to-colors": { isWorking: false }
};

const missingImpls = {
  // Can guess what's missing based on tools being 'false' in config
};

function formatCategory(category) {
   if (!category) return "Misc";
   return category.charAt(0).toUpperCase() + category.slice(1);
}

let md = "# Complete Tools Inventory\n\n";
md += "| ID | Toolkit | Tool Name | Current Status | What's Missing | Fix Priority |\n";
md += "|----|---------|-----------|----------------|----------------|--------------|\n";

RAW_TOOLS.forEach((t, i) => {
  const isWorking = toolsConfig[t.id]?.isWorking ?? false;
  const status = isWorking ? "Working" : "Coming Soon";
  const missing = isWorking ? "Nothing" : "Full implementation";
  const priority = isWorking ? "Done" : "High";
  md += `| ${i + 1} | ${formatCategory(t.categoryId)} | ${t.name} | ${status} | ${missing} | ${priority} |\n`;
});

fs.writeFileSync('COMPLETE_TOOLS_INVENTORY.md', md);
console.log('Inventory written to COMPLETE_TOOLS_INVENTORY.md');
